-- Create Database

CREATE DATABASE [PatientDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PatientDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PatientDB.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PatientDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PatientDB_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [PatientDB] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [PatientDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PatientDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PatientDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PatientDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PatientDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [PatientDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PatientDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PatientDB] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [PatientDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PatientDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PatientDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PatientDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PatientDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PatientDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PatientDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PatientDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PatientDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PatientDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PatientDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PatientDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PatientDB] SET  READ_WRITE 
GO
ALTER DATABASE [PatientDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PatientDB] SET  MULTI_USER 
GO
ALTER DATABASE [PatientDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PatientDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PatientDB] SET DELAYED_DURABILITY = DISABLED 
GO
USE [PatientDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [PatientDB]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [PatientDB] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

-- Create Table

USE [PatientDB]
GO

/****** Object:  Table [dbo].[PatientTable]    Script Date: 4/27/2019 2:15:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PatientTable](
	[PatientId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nchar](25) NULL,
	[Surname] [nchar](25) NULL,
 CONSTRAINT [PK_PatientTable] PRIMARY KEY CLUSTERED 
(
	[PatientId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Insert Table

USE [PatientDB]
GO

INSERT INTO [dbo].[PatientTable]
           ([Name]
           ,[Surname])
     VALUES
           ('Hazel','Green'),
           ('Ashley','Marshall'),
           ('Ansley','Green'),
           ('Alcock','Chapman'),
           ('Meadow','Taylor'),
           ('Green','Wright'),
           ('Paxton','Foster'),
           ('Jones','Collins')
GO


